# Site settings
title:          Nhật
description:    ""
baseurl:        "/write"
url:            "https://nhatminhbui.github.io"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Nhat Bui
  url:          https://nhatminhbui.github.io
  email:        nhatbui@gmx.com

# Build settings
markdown:       kramdown
include:
  - _pages
  - images

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:


remote_theme: chesterhow/tale

